use std::path::PathBuf;

use serde::{Deserialize, Serialize};

pub use state::VpnState;
pub use state::{default_state_file, is_tor_vpn_process};

/// Status reported to the frontend via events and commands.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "status")]
pub enum VpnStatus {
    #[serde(rename = "disconnected")]
    Disconnected,
    #[serde(rename = "connected")]
    Connected {
        state: VpnState,
        uptime_secs: u64,
        tx_rate: f64,
        rx_rate: f64,
    },
    #[serde(rename = "dirty")]
    Dirty { state: VpnState },
}

/// Full configuration exposed to the frontend via Tauri IPC.
///
/// Assembled from two sources on load:
/// - `daemon_path` from `config.json` (UI-only setting)
/// - All daemon fields from `daemon.conf` via [`config::Config`]
///
/// `#[serde(flatten)]` keeps the JSON shape flat — frontend sees one object.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UiConfig {
    pub daemon_path: String,
    #[serde(default)]
    pub minimize_to_tray: bool,
    #[serde(default = "default_true")]
    pub disconnect_on_quit: bool,
    #[serde(flatten)]
    pub daemon: config::Config,
}

fn default_true() -> bool {
    true
}

impl Default for UiConfig {
    fn default() -> Self {
        Self {
            daemon_path: find_daemon_path(),
            minimize_to_tray: false,
            disconnect_on_quit: true,
            daemon: config::Config::default(),
        }
    }
}

// ---------------------------------------------------------------------------
// UI-only settings (config.json)
// ---------------------------------------------------------------------------

/// Settings persisted to `config.json` — UI-only, not passed to the daemon.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct UiSettings {
    daemon_path: String,
    /// Hide window to tray instead of minimizing to taskbar (default: false).
    #[serde(default)]
    minimize_to_tray: bool,
    /// Disconnect VPN daemon when the UI app quits (default: true).
    #[serde(default = "default_true")]
    disconnect_on_quit: bool,
}

impl Default for UiSettings {
    fn default() -> Self {
        Self {
            daemon_path: find_daemon_path(),
            minimize_to_tray: false,
            disconnect_on_quit: true,
        }
    }
}

fn load_ui_settings() -> UiSettings {
    let path = config_file_path();
    if path.exists() {
        if let Ok(content) = std::fs::read_to_string(&path) {
            if let Ok(settings) = serde_json::from_str(&content) {
                return settings;
            }
        }
    }
    UiSettings::default()
}

fn save_ui_settings(settings: &UiSettings) -> Result<(), String> {
    let dir = config_dir();
    std::fs::create_dir_all(&dir).map_err(|e| format!("Failed to create config dir: {e}"))?;
    let json = serde_json::to_string_pretty(settings)
        .map_err(|e| format!("Failed to serialize settings: {e}"))?;
    std::fs::write(config_file_path(), json).map_err(|e| format!("Failed to write settings: {e}"))
}

// ---------------------------------------------------------------------------
// Daemon config (daemon.conf) — torrc-style, single source of truth
// ---------------------------------------------------------------------------

/// Path for the daemon config file generated by the UI.
pub fn daemon_config_path() -> PathBuf {
    config_dir().join("daemon.conf")
}

/// Log file path for the daemon (used in daemon.conf and by log reader).
///
/// Uses hardcoded `/tmp/` on macOS (not `std::env::temp_dir()` which is per-user —
/// the daemon runs as root but the UI reads the log as a regular user).
pub fn daemon_log_path() -> PathBuf {
    #[cfg(target_os = "macos")]
    {
        return PathBuf::from("/tmp/tor-vpn-daemon.log");
    }
    #[allow(unreachable_code)]
    std::env::temp_dir().join("tor-vpn-daemon.log")
}

/// Load daemon settings from `daemon.conf`, returning defaults if not present.
fn load_daemon_settings() -> config::Config {
    let path = daemon_config_path();
    if !path.exists() {
        return config::Config::default();
    }
    match config::parse_config_file(&path) {
        Ok(parsed) => config::Config::from(parsed),
        Err(e) => {
            eprintln!("[tor-vpn-ui] Warning: failed to parse daemon.conf: {e}");
            config::Config::default()
        }
    }
}

/// Save daemon settings to `daemon.conf`.
fn save_daemon_conf(settings: &config::Config) -> Result<(), String> {
    let path = daemon_config_path();
    let content = settings.to_config_content(&daemon_log_path());

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("Failed to create config dir: {e}"))?;
    }

    std::fs::write(&path, &content).map_err(|e| format!("Failed to write daemon config: {e}"))
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Platform-specific config directory for the UI application.
fn config_dir() -> PathBuf {
    #[cfg(target_os = "macos")]
    {
        let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".to_string());
        PathBuf::from(home).join("Library/Application Support/com.tor-vpn.ui")
    }
    #[cfg(target_os = "linux")]
    {
        let config = std::env::var("XDG_CONFIG_HOME").unwrap_or_else(|_| {
            let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".to_string());
            format!("{home}/.config")
        });
        PathBuf::from(config).join("tor-vpn-ui")
    }
    #[cfg(target_os = "windows")]
    {
        let appdata = std::env::var("APPDATA").unwrap_or_else(|_| "C:\\".to_string());
        PathBuf::from(appdata).join("tor-vpn-ui")
    }
}

fn config_file_path() -> PathBuf {
    config_dir().join("config.json")
}

fn find_daemon_path() -> String {
    // 1. Check for bundled sidecar (next to the UI executable)
    if let Some(path) = find_sidecar_path() {
        return path;
    }
    // 2. Fallback: search PATH
    which::which("tor-vpn")
        .map(|p| p.to_string_lossy().into_owned())
        .unwrap_or_else(|_| "tor-vpn".to_string())
}

/// Check for a bundled sidecar binary next to the UI executable.
///
/// Tauri places `externalBin` binaries in the same directory as the main
/// executable on all platforms (macOS: `App.app/Contents/MacOS/`, Linux:
/// `/usr/bin/`, Windows: install dir).
fn find_sidecar_path() -> Option<String> {
    let exe = std::env::current_exe().ok()?;
    let dir = exe.parent()?;
    let name = if cfg!(windows) {
        "tor-vpn.exe"
    } else {
        "tor-vpn"
    };
    let sidecar = dir.join(name);
    if sidecar.is_file() {
        Some(sidecar.to_string_lossy().into_owned())
    } else {
        None
    }
}

/// Resolve a setting from daemon.conf, falling back to a default value.
///
/// Reads and parses `daemon.conf` once, then extracts the desired field
/// via the `extractor` closure. Returns the default if the file doesn't
/// exist, can't be parsed, or the field is `None`.
pub fn resolve_daemon_setting<T>(
    extractor: impl FnOnce(&config::ConfigFile) -> Option<T>,
    default: impl FnOnce() -> T,
) -> T {
    let conf = daemon_config_path();
    if conf.exists() {
        if let Ok(parsed) = config::parse_config_file(&conf) {
            if let Some(value) = extractor(&parsed) {
                return value;
            }
        }
    }
    default()
}

/// Load VPN state from the daemon's state file.
///
/// Checks daemon.conf for a custom `StateFile` directive, falling back
/// to the platform default.
pub fn load_vpn_state() -> Option<VpnState> {
    let path = resolve_daemon_setting(|c| c.state_file.clone(), default_state_file);
    let content = std::fs::read_to_string(path).ok()?;
    serde_json::from_str(&content).ok()
}

// ---------------------------------------------------------------------------
// Tauri commands
// ---------------------------------------------------------------------------

/// Load full config: `daemon_path` from `config.json`, daemon fields from `daemon.conf`.
#[tauri::command]
pub fn get_config() -> Result<UiConfig, String> {
    let settings = load_ui_settings();
    let daemon = load_daemon_settings();
    Ok(UiConfig {
        daemon_path: settings.daemon_path,
        minimize_to_tray: settings.minimize_to_tray,
        disconnect_on_quit: settings.disconnect_on_quit,
        daemon,
    })
}

/// Save config: UI fields → `config.json`, daemon fields → `daemon.conf`.
#[tauri::command]
pub fn save_config(config: UiConfig) -> Result<(), String> {
    save_ui_settings(&UiSettings {
        daemon_path: config.daemon_path,
        minimize_to_tray: config.minimize_to_tray,
        disconnect_on_quit: config.disconnect_on_quit,
    })?;
    save_daemon_conf(&config.daemon)
}

/// Read saved daemon_path from config.json (same path the button uses).
pub fn saved_daemon_path() -> String {
    load_ui_settings().daemon_path
}

/// Read minimize_to_tray setting (for window close handler).
pub fn should_minimize_to_tray() -> bool {
    load_ui_settings().minimize_to_tray
}

/// Read disconnect_on_quit setting (for app exit handler).
pub fn should_disconnect_on_quit() -> bool {
    load_ui_settings().disconnect_on_quit
}

#[tauri::command]
pub fn get_daemon_path() -> String {
    find_daemon_path()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_config() {
        let config = UiConfig::default();
        assert_eq!(config.daemon.tun_name, "torvpn0");
        assert_eq!(
            config.daemon.tun_address,
            "10.200.0.1".parse::<std::net::Ipv4Addr>().unwrap()
        );
        assert_eq!(config.daemon.tun_netmask, 24);
        assert_eq!(config.daemon.tun_mtu, 1500);
        assert!(matches!(
            config.daemon.isolation,
            config::IsolationPolicy::PerDestination
        ));
        assert_eq!(config.daemon.max_connections, 256);
        assert_eq!(config.daemon.state_write_interval, 60);
        assert!(!config.daemon.override_dns);
    }

    #[test]
    fn test_vpn_state_deserialization() {
        let json = r#"{"pid":1234,"tun_name":"utun7","original_gateway":"192.168.1.1","original_interface":"en0","guard_ips":["1.2.3.4"],"bypass_cidrs":[],"tx_bytes":1024,"rx_bytes":2048}"#;
        let state: VpnState = serde_json::from_str(json).unwrap();
        assert_eq!(state.pid, 1234);
        assert_eq!(state.tx_bytes, 1024);
        assert_eq!(state.rx_bytes, 2048);
    }

    #[test]
    fn test_vpn_status_serialization() {
        let status = VpnStatus::Disconnected;
        let json = serde_json::to_string(&status).unwrap();
        assert!(json.contains("\"status\":\"disconnected\""));

        let status = VpnStatus::Dirty {
            state: VpnState::default(),
        };
        let json = serde_json::to_string(&status).unwrap();
        assert!(json.contains("\"status\":\"dirty\""));
    }

    #[test]
    fn test_ui_settings_serialization() {
        let settings = UiSettings {
            daemon_path: "/usr/local/bin/tor-vpn".to_string(),
            minimize_to_tray: false,
            disconnect_on_quit: true,
        };
        let json = serde_json::to_string(&settings).unwrap();
        assert!(json.contains("daemon_path"));
        assert!(json.contains("disconnect_on_quit"));
        assert!(!json.contains("tun_name"));
    }

    /// Verify serde(flatten) produces the flat JSON shape the frontend expects.
    #[test]
    fn test_ui_config_flat_json() {
        let config = UiConfig::default();
        let json = serde_json::to_string(&config).unwrap();
        // All fields at top level, no nested "daemon" key
        assert!(json.contains("\"daemon_path\""));
        assert!(json.contains("\"tun_name\""));
        assert!(json.contains("\"isolation\""));
        assert!(json.contains("\"socket_path\""));
        assert!(!json.contains("\"daemon\""));
    }

    /// Verify flat JSON from frontend deserializes correctly.
    #[test]
    fn test_ui_config_flat_json_roundtrip() {
        let json = r#"{
            "daemon_path": "/usr/bin/tor-vpn",
            "tun_name": "mytun",
            "tun_address": "10.100.0.1",
            "tun_netmask": 16,
            "tun_mtu": 1400,
            "isolation": "session",
            "cache_dir": "/tmp/cache",
            "bypass_cidrs": ["10.0.0.0/8"],
            "max_connections": 512,
            "max_dns_queries": 128,
            "dns_cache_ttl": 300,
            "override_dns": true,
            "exit_country": "US",
            "bridges": ["obfs4 1.2.3.4:443 AAAA"],
            "pt_paths": ["obfs4=/usr/bin/obfs4proxy"],
            "socket_path": "/tmp/custom.sock",
            "state_write_interval": 5
        }"#;
        let config: UiConfig = serde_json::from_str(json).unwrap();
        assert_eq!(config.daemon_path, "/usr/bin/tor-vpn");
        assert_eq!(config.daemon.tun_name, "mytun");
        assert_eq!(config.daemon.isolation, config::IsolationPolicy::Session);
        assert_eq!(config.daemon.bridges.len(), 1);
        assert_eq!(
            config.daemon.socket_path,
            std::path::PathBuf::from("/tmp/custom.sock")
        );
    }
}
